### ISSUE TITLE
Client is not on a valid IP address

### ISSUE THREAD

**Issue by wleoncio** [LCBC-UiO/nettskjemar#14]
This might be related to #11, but even on a plain network the following gives me an error I can't get around:

```r
> nettskjema_get_data(202524) # a test, open skjema I created
Error: Nettskjema API request failed with error
 403 : Client is not on a valid IP address
```

Token seems to be OK, given that `nettskjema_token_expiry()` returns the following:

```r
Token with name 'NETTSKJEMA_API_TOKEN' expires in 251 days.
[1] "2022-05-10"
```

Trying this from my personal WiFi at home, haven't tested it on campus (or any Eduroam connection for that matter). Should it work here?

**Comment by Athanasiamo** [comment]
Hi!

Yes, when using different networks things can get painful at times. I've had this battle so many times.

One _key_ thing about the nettskjema API tokens is that you need to create a token that lists all the IPs you might be using. I find myself having to make new tokens fairly regularly as I work from home/office/android hotspot etc. Its annoying, but this is how USIT have created the nettskjema API to work. 

This is why when you initiate a user/token creation through the nettskjemar package, you should also get the IP address of the computer you are currently on, so that you can add it to the list of IPs that are valid for your token. I should make this clearer in the documentation, as it only brushes through this important detail.

So the end message is: find what your IP address is and create a new token and use that token instead. That should solve your problem

**Comment by wleoncio** [comment]
Thanks, Mo! Perhaps the API could add to the error message a suggestion for the user to check if their current IP address is listed on the token?

Anyway, I've managed to move forward, but now I'm stuck here:

```r
> nettskjema_get_data(156018) # tried all IDs from my skjemaer, same result
Error: Nettskjema API request failed with error
 403 : No access to form with id 156018.
```

I got a feeling I am missing something silly.

**Comment by Athanasiamo** [comment]
Thanks for the suggestion. I'll see about that. Currently, the error messages are returned as is from the Nettskjema API (i.e. what USIT have created). But I'll contact them and ask if they could consider adding such a message to the error, because I think its definitely one of the most common reasons for struggling to get access to the forms.

I really thought I had made documentation on adding your API user to the forms, but it seems that was only in my head.
What you need to do, is add your api user to the people that have access to your forms. You see, USIT have not yet connected the nettskjema API users to our UiO users, so the forms just dont know that you are the one trying to connect to it. So you need to go into _every single form_ you want to have API access from and add your api user to the list of people that should have access. So, adding `username@api` to your forms should fix the problem. 

And thanks for letting me know all this. Good documentation is top priority to help people get moving!

**Comment by wleoncio** [comment]
> Currently, the error messages are returned as is from the Nettskjema API (i.e. what USIT have created). 

Oh, that explains why I couldn't simply find the error message in the package and PR my suggestion in 😆 

> So, adding `username@api` to your forms should fix the problem.

That did it, thanks! For posterity, this is the place I added my API user:

![image](https://user-images.githubusercontent.com/8234768/131955425-3a7d7875-2a48-4930-a734-d986804c5e33.png)

So this solves this issue. I'm still getting an error when using `nettskjema_get_data()`, but that should be tracked elsewhere. Cheers!
